/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package jeu2d;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class InterfaceReplay extends javax.swing.JDialog {
    
    static File chemin;

    /**
     * Creates new form InterfaceReplay
     */
    public InterfaceReplay(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        

        initComponents();
        jButton1_launch.setVisible(false);
        jButton3_fermer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1_choisir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3_choix = new javax.swing.JLabel();
        jButton1_launch = new javax.swing.JButton();
        jButton3_fermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Sélectionner un fichier pour le replay : ");

        jButton1_choisir.setForeground(new java.awt.Color(0, 102, 102));
        jButton1_choisir.setText("Choisir :");
        jButton1_choisir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_choisirActionPerformed(evt);
            }
        });

        jLabel3_choix.setText(" ");

        jButton1_launch.setForeground(new java.awt.Color(0, 204, 0));
        jButton1_launch.setText("Lancer le replay");
        jButton1_launch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_launchActionPerformed(evt);
            }
        });

        jButton3_fermer.setForeground(new java.awt.Color(255, 0, 0));
        jButton3_fermer.setText("Fermer");
        jButton3_fermer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3_fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_fermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1_choisir)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3_choix, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1_launch)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3_fermer)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_choisir)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3_choix))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1_launch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3_fermer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_choisirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_choisirActionPerformed
                                                   
    JFileChooser fileChooser = new JFileChooser();

    // Définir le répertoire initial du JFileChooser sur le bureau dans le dossier "Replays"
    File desktop = new File(System.getProperty("user.home") + File.separator + "Desktop");
    File replaysFolder = new File(desktop, "Replays");
    fileChooser.setCurrentDirectory(replaysFolder);

    // Afficher la boîte de dialogue pour sélectionner un fichier
    int result = fileChooser.showOpenDialog(this);

    // Vérifier si l'utilisateur a sélectionné un fichier
    if (result == JFileChooser.APPROVE_OPTION) {
        // Obtenez le fichier sélectionné
        File selectedFile = fileChooser.getSelectedFile();
        chemin = selectedFile;

        // Afficher le chemin du fichier sélectionné dans jLabel3_choix
        jLabel3_choix.setText(selectedFile.getAbsolutePath());
    }
    if (chemin != null) {
        jButton1_launch.setVisible(true);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1_choisirActionPerformed

    private void jButton1_launchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_launchActionPerformed
        // TODO add your handling code here:
           // Vérifiez si le chemin du fichier est défini
    if (chemin != null) {
        // Créez une instance de Replay1
        Replay1 replay = new Replay1();
        replay.setBackground(Color.white);
        
        

        
        // Mettez à jour le fichier de joueurs dans la classe Replay1
        replay.setJoueurs((File) chemin);

        // Créez une JFrame pour afficher la fenêtre de replay
        JFrame replayFrame = new JFrame("MARCHE STP");
         replayFrame.setBackground(Color.blue);
         replayFrame.getContentPane().setBackground(Color.blue);
      
        replayFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        JLabel label = new JLabel("Replay");
        label.setFont(new Font("Arial", Font.BOLD, 32));

        replayFrame.add(label, BorderLayout.NORTH);
        replayFrame.add(replay, BorderLayout.CENTER);
        //replay.setBackground(Color.red);
        
     replay.setBackground(Color.WHITE);

      replayFrame.setBackground(Color.WHITE);
      
//replayFrame.getContentPane().setBackground(Color.WHITE);


        // Ajoutez l'instance de Replay1 à la JFrame
        replayFrame.getContentPane().add(replay);

        // Réglez la taille et la visibilité de la JFrame
        replayFrame.setSize(750, 750);
        replayFrame.setVisible(true);
       
        
        jButton3_fermer.setVisible(true);
        
    }
    }//GEN-LAST:event_jButton1_launchActionPerformed

    private void jButton3_fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_fermerActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3_fermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceReplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceReplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceReplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceReplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfaceReplay dialog = new InterfaceReplay(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_choisir;
    private javax.swing.JButton jButton1_launch;
    private javax.swing.JButton jButton3_fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3_choix;
    // End of variables declaration//GEN-END:variables
}
